upstream backend {
    server laravel:8000;
}

upstream frontend {
    server react:5173;
}

server {
    listen 80;

    location / {           
        proxy_pass http://frontend/;
    }

    location /app-service/ {
        proxy_pass http://backend/;
    }
}